flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- RSA-2.2.0
- aeson-0.11.2.0
- authenticate-oauth-1.6
- connection-0.2.5
- cookie-0.4.2.1
- crypto-api-0.13.2
- crypto-pubkey-types-0.4.3
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- entropy-0.3.7
- fail-4.9.0.0
- http-client-0.4.31
- http-client-tls-0.2.4.1
- http-conduit-2.1.11
- lens-4.14
- lens-aeson-1.0.0.5
- parallel-3.2.1.0
- pureMD5-2.1.3
- reflection-2.1.2
- tls-1.3.8
- twitter-conduit-0.2.1
- twitter-types-0.7.2.2
- twitter-types-lens-0.7.2
- x509-validation-1.6.3
resolver: ghc-8.0.1
