flags: {}
extra-package-dbs: []
packages:
- '.'
- ./twitter-types/twitter-types
- ./twitter-types/twitter-types-lens
- ./twitter-conduit
extra-deps:
- MonadPrompt-1.0.0.5
- MonadRandom-0.4.2.3
- QuickCheck-2.9.1
- RSA-2.2.0
- SHA-1.6.4.2
- aeson-0.11.2.0
- authenticate-oauth-1.6
- bytes-0.15.2
- cmdargs-0.10.14
- connection-0.2.5
- cpphs-1.20.1
- crypto-api-0.13.2
- crypto-pubkey-types-0.4.3
- derive-2.5.26
- doctest-0.11.0
- entropy-0.3.7
- erf-2.0.0.0
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- flexible-defaults-0.0.1.2
- ghc-paths-0.1.0.9
- hashable-extras-0.2.3
- haskell-src-exts-1.17.1
- hlint-1.9.35
- hostname-1.0
- hscolour-1.24.1
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- http-client-0.4.31
- http-client-tls-0.2.4.1
- http-conduit-2.1.11
- lens-4.14
- lens-aeson-1.0.0.5
- log-domain-0.10.3.1
- math-functions-0.2.0.1
- mersenne-random-pure64-0.2.0.5
- network-uri-2.6.1.0
- parallel-3.2.1.0
- parsec-3.1.11
- pem-0.2.2
- polyparse-1.12
- pureMD5-2.1.3
- quickcheck-io-0.1.3
- random-extras-0.19
- random-fu-0.2.7.0
- random-shuffle-0.0.4
- random-source-0.3.0.6
- refact-0.3.0.2
- reflection-2.1.2
- regex-base-0.93.2
- regex-posix-0.95.2
- rvar-0.2.0.3
- safecopy-0.9.1
- setenv-0.1.1.3
- socks-0.5.5
- stateref-0.3
- syb-0.6
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- test-framework-quickcheck2-0.3.0.3
- tf-random-0.5
- th-extras-0.0.0.4
- tls-1.3.8
- uniplate-1.6.12
- vector-th-unbox-0.2.1.6
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- xml-1.3.14
resolver: ghc-8.0.1
